addSbtPlugin("pl.project13.scala" % "sbt-jmh"              % "0.3.3")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"         % "2.0")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"              % "1.1.0")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"        % "1.5.1")
addSbtPlugin("net.virtual-void"   % "sbt-dependency-graph" % "0.9.2")
addSbtPlugin("com.eed3si9n"       % "sbt-assembly"         % "0.14.8")