version: '2'
services:
  infinispan:
    image: jboss/infinispan-server:9.4.5.Final
    command: standalone -Djboss.bind.address.management=0.0.0.0
    environment:
      APP_USER: "trembita"
      APP_PASS: "trembita"
    ports:
      - "8082:8080"
      - "11222:11222"