package com.examples.complex

case class CsvRecord(id: Long,
                     caseNumber: String,
                     date: String,
                     block: String,
                     IUCR: String,
                     primaryType: String,
                     description: String,
                     locationDescription: String,
                     arrest: Boolean,
                     domestic: Boolean,
                     beat: String,
                     district: String,
                     ward: String,
                     communityArea: String,
                     FBICode: String,
                     xCoordinate: Option[Long],
                     yCoordinate: Option[Long],
                     year: Int,
                     updatedOn: String,
                     latitude: Option[Double],
                     longitude: Option[Double],
                     location: Option[String],
                     address: Option[String] = None)
